### ISSUE TITLE
FEATURE: auto-build a docker image

### ISSUE THREAD

**Issue by LordVeovis** [Kwoth/NadekoBot#2556]
Objective of this new feature: propose an automatically built Docker image

Benefits:
* very simple (aka easy to review or maintain) build script
* light (280MB vs 2GB with the current available images)
* simple architecture (1 docker = 1 service)
* auto-build a latest tagged image when something is pushed on branch 1.9
* auto-build a version tagged image when a new git tag is created (or some tags only by using a regexp)

The two last points are only available when the Dockerfile is part of the source code when using the autobuild feature of the dockerhub platform.

This is the using Dockerfile I'm using currently. This Dockerfile is not the one to be merged, it has an extra step which is the git clone (step already done by the CI tool usually)
```
FROM microsoft/dotnet:2.1-sdk-alpine AS build

ENV TAG=1.9

RUN set -ex; \
    apk add --no-cache git; \
    git clone -b "$TAG" https://github.com/LordVeovis/NadekoBot

WORKDIR /NadekoBot/src/NadekoBot
RUN set -ex; \
    dotnet restore; \
    dotnet build -c Release; \
    dotnet publish -c Release -o /app

WORKDIR /app
RUN set -ex; \
    rm libopus.so libsodium.dll libsodium.so opus.dll; \
    find . -type f -exec chmod -x {} \;; \
    rm -R runtimes/win* runtimes/osx* runtimes/linux-*

FROM microsoft/dotnet:2.1-runtime-alpine AS runtime
WORKDIR /app
COPY --from=build /app /app
RUN set -ex;\
    apk add --no-cache \
        ffmpeg \
        youtube-dl \
        libsodium \
        opus; \
    adduser -D nadeko; \
    chown nadeko /app; \
    chmod u+w /app; \
    install -d -o nadeko -g nadeko -m 755 /app/data

# workaround for the runtime to find the native libs loaded through DllImport
RUN set -ex; \
    ln -s /usr/lib/libopus.so.0 /app/libopus.so; \
    ln -s /usr/lib/libsodium.so.23 /app/libsodium.so

VOLUME [ "/app/data" ]
USER nadeko
CMD ["dotnet", "/app/NadekoBot.dll"]
```

And the docker-compose.yml to run the Nadeko stack:
```
version: "3.5"
services:
  nadeko:
    #image: willysunny/nadecker:latest
    build: .
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
    volumes:
      - /docker/nadeko/conf/credentials.json:/app/credentials.json:ro
      - /docker/nadeko/data:/app/data

  redis:
    image: redis:alpine
    sysctls:
      net.core.somaxconn: 511
```

NSFW and Music, the most important feature of Nadeko ;), seems to work.
A little detail remains: I don't know the equivalent of LD_LIBRARY_PATH for .netcore2, if such a thing exists (https://github.com/dotnet/coreclr/issues/930)

As a note: the files in /app/data MUST be owned by the user 1000 (nadeko inside the container)
